### ISSUE TITLE
Content agnosticism

### ISSUE THREAD

**Issue by ekr** [IRTF-HRPC/draft-guidelines#3] opened 2023-03-31 03:17 UTC
>   Question(s): If your protocol impacts packet handling, does it use
   user data (packet data that is not included in the header)?  Is it
   making decisions based on the payload of the packet?  Does your
   protocol enable the prioritization of certain content or services
   over others in the routing process?  Is the protocol transparent
   about the prioritization that is made (if any)?
>
>   Explanation: Content agnosticism refers to the notion that network
   traffic is treated identically regardless of payload, with some
   exceptions where it comes to effective traffic handling, for instance
   where it comes to delay-tolerant or delay-sensitive packets, based on
   the header.  If there is any prioritization based on the content or
   metadata of the protocol, the protocol should be transparent about
   such information and reasons thereof.
>
>   Example: Content agnosticism prevents payload-based discrimination
   against packets.  This is important because changes to this principle
   can lead to a two-tiered Internet, where certain packets are
   prioritized over others on the basis of their content.  Effectively
   this would mean that although all users are entitled to receive their
   packets at a certain speed, some users become more equal than others.

Two points. This seems like it's conflating two separate things:

1. Whether protocols include mechanisms that permit differential treatment based on payload.
2. Whether the networks are in fact doing differential treatment.

I would have expected that "content agnosticism" would refer to the latter, not the former, and that if you wanted a name for the former, I would use some term like "indistinguishability".

Second, I think it's important to distinguish *traffic class/type* from *traffic origin*. For instance, one might imagine treating video differently than text, but prioritize all video sources the same. One might also imagine treating Netflix differently from Amazon. This brings us to the question of "users". As I said, this isn't really a matter of treating different end-users differently but rather of network services. I guess Netflix is a user, but that's not the conventional terminology.

On a broader note, I just think trying to sort out principles around traffic class discrimination is quite difficult. I think we all agree that networks don't need to carry traffic to/from non-subscribers, and I don't think it's that controversial that subscribers might be able to buy faster speeds on the same infrastructure, so I think trying to draw the line between acceptable and unacceptable traffic class discrimination is quite difficult. A lot of the IETF security work has tended towards trying to make that kind of discrimination more difficult, largely in favor of other values (more filtering and surveillance than performance degradation), and that has other side effects.

**Comment by nllz** [comment] 2023-05-14 11:36
Thanks for this comment - I think it makes a lot of sense to expand the notion to also include origin, destination, _and_ payload discrimination discrimination. Please see the following text suggestion below:  

Question(s): If your protocol impacts packet handling, does it use user data (packet data that is not included in the header)? Is it making decisions based on the payload of the packet? Does your
protocol enable the prioritization of certain content or services over others in the routing process? Does your protocol allow discrimination of traffic based on its origin? Is the protocol transparent about the prioritization that is made (if any)?

Explanation: Content agnosticism refers to the notion that network traffic is treated identically regardless of origin, destination or payload, with some exceptions where it comes to effective traffic handling, for instance where it comes to delay-tolerant or delay-sensitive packets, based on the header. If there is any prioritization based on the content or metadata of the protocol, the protocol should be transparent about such information and reasons thereof.

Example: Content agnosticism prevents origin or payload-based discrimination against packets. This is important because changes to this principle can lead to a two-tiered Internet, where certain packets are prioritized over others on the basis of their content. Effectively this would mean that although all users are entitled to receive their packets at a certain speed, some users become more equal than others.

**Comment by ekr** [comment] 2023-06-08 23:31
> Question(s): If your protocol impacts packet handling, does it use user data (packet data that is not included in the header)? Is it making decisions based on the payload of the packet? Does your
protocol enable the prioritization of certain content or services over others in the routing process? Does your protocol allow discrimination of traffic based on its origin? Is the protocol transparent about the prioritization that is made (if any)?

This seems like kind of a confusing set of questions. First, I don't know what "impacts packet handling" means. For instance, QUIC uses packet data and makes decisions based on the payload of the packet. It allows for discrimination based on origin (because there is an IP address) and I'm not sure what it would mean for it to be transparent about the prioritization because it would be some intermediate network element that is doing the prioritization unbeknownst to QUIC. I think we would generally agree that QUIC is designed in a way to minimize network interference, but the answers to these questions would suggest otherwise, so they don't seem like they are very useful.

As I said initially, I think there are two concepts here:

> 
 >   Whether protocols include mechanisms that permit differential treatment based on payload.
>    Whether the networks are in fact doing differential treatment.

> I would have expected that "content agnosticism" would refer to the latter, not the former, and that if you wanted a name for the former, I would use some term like "indistinguishability".



Before we try to wordsmith, I think we should sort out what this text is trying to say. For instance:

(1) protocols should be designed to minimize unnecessary data leakage that could be used for differential treatment.
(2) protocols shouldn't add features that are used for differential treatment
(3) networks shouldn't do differential treatment.

Or some other thing.







Explanation: Content agnosticism refers to the notion that network traffic is treated identically regardless of origin, destination or payload, with some exceptions where it comes to effective traffic handling, for instance where it comes to delay-tolerant or delay-sensitive packets, based on the header. If there is any prioritization based on the content or metadata of the protocol, the protocol should be transparent about such information and reasons thereof.

> Example: Content agnosticism prevents origin or payload-based discrimination against packets. This is important because changes to this principle can lead to a two-tiered Internet, where certain packets are prioritized over others on the basis of their content. Effectively this would mean that although all users are entitled to receive their packets at a certain speed, some users become more equal than others.

**Comment by gurshabad** [comment] 2023-06-12 12:16
> (1) protocols should be designed to minimize unnecessary data leakage that could be used for differential treatment.
> (2) protocols shouldn't add features that are used for differential treatment
> (3) networks shouldn't do differential treatment.
> 

I think the text is trying to address all three. I agree that the text should be clearer in distinguishing amongst these concepts.

> It allows for discrimination based on origin (because there is an IP address) and I'm not sure what it would mean for it to be transparent about the prioritization because it would be some intermediate network element that is doing the prioritization unbeknownst to QUIC. I think we would generally agree that QUIC is designed in a way to minimize network interference, but the answers to these questions would suggest otherwise, so they don't seem like they are very useful.

I think this is a good illustration. The transparency about prioritization is more applicable to the deployment than the design of the protocol itself in this case. 

As a starting point, how is this?

> Question(s): Does your protocol include plaintext elements, either in the payload or headers, that can be used for differential treatment? Is there a way minimise leaking of such data over the network? If not, is there a way for deployments of the protocol to make the differential treatment (including prioritisation of certain traffic), if any,  transparent?
>

**Comment by ekr** [comment] 2023-06-22 21:58
> Question(s): Does your protocol include plaintext elements, either in the payload or headers, that can be used for differential treatment? Is there a way minimise leaking of such data over the network?

This part seems fine.

> If not, is there a way for deployments of the protocol to make the differential treatment (including prioritisation of certain traffic), if any, transparent?

This less so, for several reasons:

- Even if the protocol doesn't leak *any* information, other protocols might and that could be used for traffic  discrimination. For instance, I understand IP address is commonly used.
- We have at times explicitly designed protocols with mechanisms to signal their contents to the network (see ALPN, DSCP). 
- I'm not aware of any common protocol that involves the network signaling prioritization to the endpoints. Are you? If not, then this seems unhelpful.

But I think the bigger problem here is that I don't really think there is consensus about what forms of traffic prioritization are appropriate. For instance, suppose that I sell two grades of network provision, "fast" and "slow" and use the IP address to determine packet treatment. Is this document taking the position that that is bad? That seems like a radical position. So, before trying to write text that goes in the document, I think it would be useful to try to describe what types of prioritization you are arguing are appropriate and which ones you think are inappropriate, and what the dividing principle is.

**Comment by gurshabad** [comment] 2023-06-26 09:48
> But I think the bigger problem here is that I don't really think there is consensus about what forms of traffic prioritization are appropriate.

To draft this guideline, I frankly don't think we need to arrive at a consensus about what forms of traffic prioritization are acceptable. The broad agreement here is that the protocol, by design, won't have elements that can be used for traffic discrimination/differentiation. 

> Even if the protocol doesn't leak any information, other protocols might and that could be used for traffic discrimination. For instance, I understand IP address is commonly used.

Sure, nothing protocol designers can do about that if what they're designing will operate over IP addresses. Maybe the guideline about 'deployment' can be sharpened here a bit.

> I'm not aware of any common protocol that involves the network signaling prioritization to the endpoints. Are you? If not, then this seems unhelpful.

Maybe you can correct me if I'm wrong, but in Diffserv, the DS field would be accessible to the network and the endpoint? While its design motivation is traffic prioritisation, its use could _technically_ be made transparent at the end.

**Comment by ekr** [comment] 2023-06-26 13:09
> To draft this guideline, I frankly don't think we need to arrive at a consensus about what forms of traffic prioritization are acceptable. The broad agreement here is that the protocol, by design, won't have elements that can be used for traffic discrimination/differentiation.

Well, as I said, given that the IETF has deliberately designed protocols with precisely this property a number of times, this seems like a fairly strong position to take, and if that truly is the RG's position then it should be very clear on it. I.e., it should say that diffserv, ALPN, (and probably even assigned port numbers!) are a mistake.

> Maybe you can correct me if I'm wrong, but in Diffserv, the DS field would be accessible to the network and the endpoint? While its design motivation is traffic prioritisation, its use could technically be made transparent at the end.

One could invent some new protocol that the network used to tell the endpoint about discrimination, but there's nothing in the spec that provides for that.

**Comment by nllz** [comment] 2023-07-08 17:22
As per the separate email thread:

I hope this helps. I made the concerns vis-a-vis net neutrality clearer and added the examples we discussed here. All suggestions, as always, are welcome.

Question(s): If your protocol impacts packet handling, does it use user data (packet data that is not included in the header)? Is it making decisions based on the payload of the packet? Does your protocol enable the prioritization of certain content or services over others in the routing process? Is the prioritization that is made auditable for negative impacts on net neutrality?

Explanation: Content agnosticism refers to the notion that network traffic is treated identically regardless of payload, with some exceptions where it comes to effective traffic handling, for instance where it comes to delay-tolerant or delay-sensitive packets, based on the header. If there is any prioritization based on the content or metadata of the protocol, the protocol should be transparent about how it does so, for instance by adding flow labels (in the case of IPv6) or the six bits available in the Differentiated Services Code Point (DSCP) (in the case of DiffServ).

Example: Content agnosticism prevents payload-based discrimination against packets. This is important because changes to this principle can lead to a two-tiered Internet, where certain packets are prioritized over others on the basis of their content, their origin, or their destination. Effectively this would mean that although all users are entitled to receive their packets at a certain speed, some users become more equal than others. However, there are many different kinds of traffic differentiation and prioritization, therefore it is extremely helpful is different use cases and their intended and possible impacts are documented.

**Comment by nllz** [comment] 2023-07-10 12:51
https://github.com/IRTF-HRPC/draft-guidelines/commit/fb0a78ed1a7a2c040ff5792b65d574cc6ac0a50a

**Comment by nllz** [comment] 2023-07-10 15:38
I propose we move the discussion back to the hrpc list based on: https://datatracker.ietf.org/doc/html/draft-irtf-hrpc-guidelines-19

**Comment by nllz** [comment] 2023-10-04 15:24
Fixed with https://github.com/IRTF-HRPC/draft-guidelines/pull/15

**Closed as completed by nllz** 2023-10-04 15:24 UTC
